server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mohang?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: travel_user
    password: secure_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

google:
  places:
    api-key: AIzaSyAZc_IfL1Ke22wgSeXjtCNd0k8Awd2unsE

openai:
  api-key: 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
